import type { Metadata } from "next";
import "./globals.css";
import { Figtree } from "next/font/google";
import { cn } from "@/lib/utils";
import { Navbar } from "@/components/navbar";
import { Footer } from "@/components/footer";

import { NuqsAdapter } from "nuqs/adapters/next/app";
import { Toaster } from "@/components/ui/sonner";
import { QueryClientProvider } from "@/providers/query-provider";
import { CartProvider } from "./(dashboard)/cart/_components/cart-provider";

const figtree = Figtree({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          `min-h-screen text-neutral-500 antialiased`,
          figtree.className
        )}
      >
        <NuqsAdapter>
          <QueryClientProvider>
            <CartProvider>{children}</CartProvider>
          </QueryClientProvider>
        </NuqsAdapter>
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
