import type { Metadata } from 'next'
import './globals.css'
import { Figtree } from 'next/font/google'
import { cn } from '@/lib/utils'
import { Navbar } from '@/components/navbar'
import { Footer } from '@/components/footer'

import { NuqsAdapter } from 'nuqs/adapters/next/app'
import { Toaster } from '@/components/ui/sonner'
import { QueryClientProvider } from '@/providers/query-provider'

const figtree = Figtree({ subsets: ['latin'], variable: '--font-sans' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={cn(
          `flex min-h-screen flex-col font-sans text-neutral-500 antialiased`,
          figtree.variable
        )}
      >
        <NuqsAdapter>
          <QueryClientProvider>
            <Navbar />
            <main className='flex-grow pt-[150px]'>{children}</main>
            <Footer />
          </QueryClientProvider>
        </NuqsAdapter>
        <Toaster />
      </body>
    </html>
  )
}
